export interface SeedStrain {
  name: string;
  type: "Indica" | "Sativa" | "Hybrid";
  ratio: string;
  thcMin: number;
  thcMax: number;
  cbdMin: number;
  cbdMax: number;
  terpenes: string[];
  effects: string[];
  negativeEffects: string[];
  flavors: string[];
  bestFor: string[];
  description: string;
  growDifficulty: "Easy" | "Moderate" | "Difficult";
  floweringTime: string;
  yieldIndoor: string;
  popularity: number;
}

export const seedStrains: SeedStrain[] = [
  {
    name: "Blue Dream",
    type: "Hybrid",
    ratio: "60% Sativa / 40% Indica",
    thcMin: 17, thcMax: 24, cbdMin: 0.1, cbdMax: 0.2,
    terpenes: ["Myrcene", "Caryophyllene", "Pinene"],
    effects: ["Relaxed", "Happy", "Euphoric", "Uplifted", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Berry", "Sweet", "Herbal"],
    bestFor: ["Creativity", "Pain", "Anxiety"],
    description: "Blue Dream is a sativa-dominant hybrid that balances full-body relaxation with gentle cerebral invigoration. A cross between Blueberry and Haze, it delivers swift symptom relief without heavy sedative effects. Its sweet berry aroma and smooth smoke have made it one of the most popular strains in the United States.",
    growDifficulty: "Easy",
    floweringTime: "9-10 weeks",
    yieldIndoor: "500-600g/m²",
    popularity: 98,
  },
  {
    name: "OG Kush",
    type: "Hybrid",
    ratio: "55% Sativa / 45% Indica",
    thcMin: 20, thcMax: 26, cbdMin: 0, cbdMax: 0.3,
    terpenes: ["Myrcene", "Limonene", "Caryophyllene"],
    effects: ["Euphoric", "Relaxed", "Happy", "Uplifted", "Hungry"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Earthy", "Pine", "Woody"],
    bestFor: ["Pain", "Anxiety", "Sleep"],
    description: "OG Kush is the genetic backbone of West Coast cannabis. With a complex terpene profile that delivers fuel, skunk, and spice aromas, this strain produces a heavy, mixed head and body effect. Despite its high THC content, OG Kush delivers a balanced experience cherished by both recreational and medical users.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 97,
  },
  {
    name: "Gorilla Glue",
    type: "Hybrid",
    ratio: "50% Sativa / 50% Indica",
    thcMin: 24, thcMax: 30, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Myrcene", "Limonene"],
    effects: ["Relaxed", "Euphoric", "Happy", "Uplifted", "Sleepy"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Diesel", "Earthy", "Pine"],
    bestFor: ["Pain", "Sleep", "Anxiety"],
    description: "Gorilla Glue (GG4) is a potent hybrid strain that delivers heavy-handed euphoria and relaxation. Named for its incredibly sticky trichomes, this multiple Cannabis Cup winner glues you to the couch. Its pungent diesel and earthy aroma signals the powerful experience to come.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "450-550g/m²",
    popularity: 96,
  },
  {
    name: "Girl Scout Cookies",
    type: "Hybrid",
    ratio: "60% Indica / 40% Sativa",
    thcMin: 25, thcMax: 28, cbdMin: 0, cbdMax: 0.2,
    terpenes: ["Caryophyllene", "Limonene", "Humulene"],
    effects: ["Euphoric", "Happy", "Relaxed", "Creative", "Uplifted"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Sweet", "Earthy", "Mint"],
    bestFor: ["Pain", "Anxiety", "Appetite"],
    description: "Girl Scout Cookies (GSC) is a celebrity strain born in California that has achieved legendary status. This OG Kush and Durban Poison cross delivers full-body relaxation combined with a cerebral high that inspires creativity. Its dessert-like sweetness and potent effects have earned it numerous awards.",
    growDifficulty: "Difficult",
    floweringTime: "9-10 weeks",
    yieldIndoor: "280-350g/m²",
    popularity: 95,
  },
  {
    name: "Sour Diesel",
    type: "Sativa",
    ratio: "90% Sativa / 10% Indica",
    thcMin: 20, thcMax: 25, cbdMin: 0, cbdMax: 0.2,
    terpenes: ["Caryophyllene", "Myrcene", "Limonene"],
    effects: ["Energetic", "Happy", "Euphoric", "Uplifted", "Creative"],
    negativeEffects: ["Dry mouth", "Paranoia", "Anxious"],
    flavors: ["Diesel", "Earthy", "Citrus"],
    bestFor: ["Focus", "Creativity", "Social"],
    description: "Sour Diesel is a fast-acting sativa named after its pungent, fuel-like aroma. This energizing strain delivers dreamy cerebral effects that fuel creativity and conversation. One of the most popular sativas in the world, Sour Diesel has become a go-to for daytime use and creative pursuits.",
    growDifficulty: "Moderate",
    floweringTime: "10-11 weeks",
    yieldIndoor: "450-500g/m²",
    popularity: 94,
  },
  {
    name: "Granddaddy Purple",
    type: "Indica",
    ratio: "100% Indica",
    thcMin: 17, thcMax: 23, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Pinene", "Caryophyllene"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Grape", "Berry", "Sweet"],
    bestFor: ["Sleep", "Pain", "Appetite"],
    description: "Granddaddy Purple is a famous indica cross between Purple Urkle and Big Bud. Its potent effects are clearly reflected in its physical and cerebral effects. GDP delivers a fusion of cerebral euphoria and physical relaxation, making it the quintessential nighttime strain for unwinding and drifting off to sleep.",
    growDifficulty: "Easy",
    floweringTime: "8-11 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 93,
  },
  {
    name: "Jack Herer",
    type: "Sativa",
    ratio: "55% Sativa / 45% Indica",
    thcMin: 18, thcMax: 24, cbdMin: 0, cbdMax: 0.3,
    terpenes: ["Terpinolene", "Pinene", "Myrcene"],
    effects: ["Happy", "Uplifted", "Energetic", "Creative", "Focused"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Pine", "Earthy", "Woody"],
    bestFor: ["Focus", "Creativity", "Social"],
    description: "Named after the legendary cannabis activist and author, Jack Herer is a sativa-dominant strain that has won numerous awards for its quality and potency. Combining a Haze hybrid with Northern Lights #5 and Shiva Skunk, it captures the cerebral elevation and creative spark that its namesake championed.",
    growDifficulty: "Moderate",
    floweringTime: "8-10 weeks",
    yieldIndoor: "400-500g/m²",
    popularity: 92,
  },
  {
    name: "White Widow",
    type: "Hybrid",
    ratio: "60% Sativa / 40% Indica",
    thcMin: 18, thcMax: 25, cbdMin: 0, cbdMax: 0.2,
    terpenes: ["Myrcene", "Caryophyllene", "Limonene"],
    effects: ["Euphoric", "Happy", "Energetic", "Creative", "Relaxed"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Earthy", "Woody", "Spicy"],
    bestFor: ["Social", "Creativity", "Focus"],
    description: "White Widow is a balanced hybrid first bred in the Netherlands. A cross between a Brazilian sativa landrace and a resin-heavy South Indian indica, White Widow has been a coffeeshop staple since the 1990s. Its white crystal resin coating warns you of the potent cerebral effects to come.",
    growDifficulty: "Easy",
    floweringTime: "8-9 weeks",
    yieldIndoor: "400-500g/m²",
    popularity: 91,
  },
  {
    name: "Northern Lights",
    type: "Indica",
    ratio: "95% Indica / 5% Sativa",
    thcMin: 16, thcMax: 21, cbdMin: 0.1, cbdMax: 0.3,
    terpenes: ["Myrcene", "Caryophyllene", "Pinene"],
    effects: ["Relaxed", "Happy", "Sleepy", "Euphoric", "Calm"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Earthy", "Sweet", "Pine"],
    bestFor: ["Sleep", "Pain", "Anxiety"],
    description: "Northern Lights stands among the most famous strains of all time. A pure indica descendant of Afghani and Thai landrace strains, Northern Lights produces resinous buds and a fast-acting body stone. Its dreamy euphoria has made it a foundational strain in breeding programs worldwide.",
    growDifficulty: "Easy",
    floweringTime: "7-8 weeks",
    yieldIndoor: "450-500g/m²",
    popularity: 90,
  },
  {
    name: "Purple Haze",
    type: "Sativa",
    ratio: "85% Sativa / 15% Indica",
    thcMin: 17, thcMax: 20, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Caryophyllene", "Limonene"],
    effects: ["Euphoric", "Happy", "Creative", "Energetic", "Uplifted"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Berry", "Earthy", "Sweet"],
    bestFor: ["Creativity", "Social", "Focus"],
    description: "Purple Haze is a classic sativa-dominant strain immortalized by Jimi Hendrix. Known for its high-energy cerebral stimulation, Purple Haze delivers a dreamy burst of euphoria that brings veteran consumers back to their first experience. Its sweet berry flavor and creative buzz make it a beloved daytime strain.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 89,
  },
  {
    name: "Pineapple Express",
    type: "Hybrid",
    ratio: "60% Sativa / 40% Indica",
    thcMin: 17, thcMax: 24, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Pinene"],
    effects: ["Happy", "Euphoric", "Uplifted", "Energetic", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Tropical", "Citrus", "Sweet"],
    bestFor: ["Social", "Creativity", "Focus"],
    description: "Pineapple Express combines the potent and flavorful forces of parent strains Trainwreck and Hawaiian. The smell is likened to fresh apple and mango, with a taste of pineapple, pine, and cedar. This hard-hitting hybrid provides a long-lasting energetic buzz perfect for productive afternoons and creative escapes.",
    growDifficulty: "Easy",
    floweringTime: "7-8 weeks",
    yieldIndoor: "450-500g/m²",
    popularity: 88,
  },
  {
    name: "Wedding Cake",
    type: "Hybrid",
    ratio: "60% Indica / 40% Sativa",
    thcMin: 24, thcMax: 27, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Caryophyllene", "Myrcene"],
    effects: ["Relaxed", "Euphoric", "Happy", "Uplifted", "Hungry"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Sweet", "Vanilla", "Earthy"],
    bestFor: ["Pain", "Anxiety", "Appetite"],
    description: "Wedding Cake, also known as Pink Cookies, is a potent indica-hybrid cross of Girl Scout Cookies and Cherry Pie. This strain earns its name from its rich, tangy flavor profile with undertones of earthy pepper. Its relaxing and euphoric effects calm the body while providing mental stimulation.",
    growDifficulty: "Moderate",
    floweringTime: "7-9 weeks",
    yieldIndoor: "450-500g/m²",
    popularity: 87,
  },
  {
    name: "Gelato",
    type: "Hybrid",
    ratio: "55% Indica / 45% Sativa",
    thcMin: 20, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Caryophyllene", "Humulene"],
    effects: ["Euphoric", "Happy", "Relaxed", "Creative", "Uplifted"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Sweet", "Citrus", "Berry"],
    bestFor: ["Creativity", "Pain", "Anxiety"],
    description: "Gelato is a delicious hybrid strain from the Cookie Fam and Sherbinski, crossing Sunset Sherbet with Thin Mint Cookies. This strain delivers a balanced high that produces feelings of euphoria, creativity, and relaxation. Its sweet sherbet-like flavor with fruity undertones has made it a dispensary favorite nationwide.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 86,
  },
  {
    name: "Zkittlez",
    type: "Indica",
    ratio: "70% Indica / 30% Sativa",
    thcMin: 15, thcMax: 23, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Linalool", "Humulene"],
    effects: ["Relaxed", "Happy", "Euphoric", "Sleepy", "Focused"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Berry", "Sweet", "Tropical"],
    bestFor: ["Anxiety", "Pain", "Sleep"],
    description: "Zkittlez is an indica-dominant strain that took the cannabis world by storm with its incredible fruit-forward flavor profile. A cross of Grape Ape and Grapefruit, Zkittlez is known for its calming effects that settle you into a content, carefree state. Its award-winning genetics deliver a mellow experience.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "400-500g/m²",
    popularity: 85,
  },
  {
    name: "Runtz",
    type: "Hybrid",
    ratio: "50% Indica / 50% Sativa",
    thcMin: 19, thcMax: 29, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Linalool"],
    effects: ["Euphoric", "Happy", "Relaxed", "Tingly", "Giggly"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Sweet", "Tropical", "Berry"],
    bestFor: ["Anxiety", "Pain", "Social"],
    description: "Runtz is an evenly balanced hybrid strain created by crossing Zkittlez with Gelato. Named after the colorful candy, Runtz brings a fruity flavor profile with tropical citrus and sour berries. Its creamy smoke delivers a euphoric high that builds into a calming body relaxation, perfect for any time of day.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 84,
  },
  {
    name: "Durban Poison",
    type: "Sativa",
    ratio: "100% Sativa",
    thcMin: 15, thcMax: 25, cbdMin: 0, cbdMax: 0.2,
    terpenes: ["Terpinolene", "Myrcene", "Ocimene"],
    effects: ["Energetic", "Uplifted", "Happy", "Focused", "Creative"],
    negativeEffects: ["Dry mouth", "Paranoia", "Anxious"],
    flavors: ["Earthy", "Sweet", "Pine"],
    bestFor: ["Focus", "Creativity", "Social"],
    description: "Durban Poison is a pure sativa originating from the South African port city of Durban. This landrace strain has been prized for generations for its sweet smell and energetic, uplifting effects. Its clear-headed, stimulating high makes it a perfect daytime strain for staying productive and creative.",
    growDifficulty: "Easy",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-450g/m²",
    popularity: 83,
  },
  {
    name: "Green Crack",
    type: "Sativa",
    ratio: "65% Sativa / 35% Indica",
    thcMin: 15, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Caryophyllene", "Pinene"],
    effects: ["Energetic", "Focused", "Happy", "Uplifted", "Creative"],
    negativeEffects: ["Dry mouth", "Paranoia", "Anxious"],
    flavors: ["Citrus", "Sweet", "Tropical"],
    bestFor: ["Focus", "Creativity", "Social"],
    description: "Green Crack is a potent sativa originally named Cush by its breeder Cecil C, then renamed by Snoop Dogg. A cross of Skunk #1, it induces an invigorating mental buzz that keeps you going throughout the day. Its sharp tangy citrus flavor and energetic high have made it a daytime favorite.",
    growDifficulty: "Easy",
    floweringTime: "7-9 weeks",
    yieldIndoor: "450-500g/m²",
    popularity: 82,
  },
  {
    name: "AK-47",
    type: "Hybrid",
    ratio: "65% Sativa / 35% Indica",
    thcMin: 13, thcMax: 20, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Caryophyllene", "Pinene"],
    effects: ["Happy", "Uplifted", "Relaxed", "Euphoric", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Earthy", "Sweet", "Floral"],
    bestFor: ["Social", "Creativity", "Anxiety"],
    description: "Despite its intimidating name, AK-47 delivers a steady, even-keeled buzz that keeps you mentally alert and creative while relaxing the body. This sativa-dominant hybrid blends Colombian, Mexican, Thai, and Afghani varieties, producing a complex aroma of sour earthiness with sweet floral notes.",
    growDifficulty: "Easy",
    floweringTime: "7-9 weeks",
    yieldIndoor: "350-500g/m²",
    popularity: 81,
  },
  {
    name: "Bubba Kush",
    type: "Indica",
    ratio: "80% Indica / 20% Sativa",
    thcMin: 15, thcMax: 22, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Coffee", "Earthy", "Sweet"],
    bestFor: ["Sleep", "Pain", "Anxiety"],
    description: "Bubba Kush is a heavy indica that has gained fame for its tranquilizing effects. Sweet hashish flavors with subtle notes of chocolate and coffee dominate the flavor profile. This strain settles in quickly, melting away stress and physical discomfort and leaving you in a blissful state of relaxation.",
    growDifficulty: "Easy",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 80,
  },
  {
    name: "Trainwreck",
    type: "Hybrid",
    ratio: "65% Sativa / 35% Indica",
    thcMin: 18, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Pinene", "Limonene"],
    effects: ["Euphoric", "Happy", "Creative", "Uplifted", "Energetic"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Pine", "Earthy", "Citrus"],
    bestFor: ["Pain", "Creativity", "Focus"],
    description: "Trainwreck is a mind-bending sativa-dominant hybrid that hits like a freight train with its potent, fast-acting effects. This cross of Mexican and Thai sativas with Afghani indicas offers a sweet lemon and spicy pine aroma. It begins with a surge of euphoria that sparks creativity and conversation.",
    growDifficulty: "Easy",
    floweringTime: "8-10 weeks",
    yieldIndoor: "400-500g/m²",
    popularity: 79,
  },
  {
    name: "Strawberry Cough",
    type: "Sativa",
    ratio: "80% Sativa / 20% Indica",
    thcMin: 15, thcMax: 23, cbdMin: 0, cbdMax: 0.2,
    terpenes: ["Myrcene", "Pinene", "Caryophyllene"],
    effects: ["Happy", "Uplifted", "Euphoric", "Energetic", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Berry", "Sweet", "Earthy"],
    bestFor: ["Social", "Anxiety", "Creativity"],
    description: "Strawberry Cough is a potent sativa named for its sweet strawberry smell and its tendency to make even experienced users cough. This uplifting strain is perfect for managing social anxiety and sparking creative thinking. Its berry-forward terpene profile delivers a smooth, expansive experience that encourages sociability.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 78,
  },
  {
    name: "Amnesia Haze",
    type: "Sativa",
    ratio: "80% Sativa / 20% Indica",
    thcMin: 20, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Limonene", "Caryophyllene"],
    effects: ["Happy", "Euphoric", "Energetic", "Uplifted", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Citrus", "Earthy", "Sweet"],
    bestFor: ["Creativity", "Focus", "Social"],
    description: "Amnesia Haze is a globally popular sativa-dominant strain that originated in the Netherlands. With its energizing and creative effects, it has won multiple Cannabis Cup awards. The strain produces an uplifting cerebral high with earthy and citrus flavors, making it a favorite for daytime creative sessions.",
    growDifficulty: "Difficult",
    floweringTime: "10-12 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 77,
  },
  {
    name: "Super Lemon Haze",
    type: "Sativa",
    ratio: "80% Sativa / 20% Indica",
    thcMin: 16, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Caryophyllene", "Myrcene"],
    effects: ["Happy", "Energetic", "Uplifted", "Euphoric", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Citrus", "Sweet", "Earthy"],
    bestFor: ["Focus", "Social", "Creativity"],
    description: "Super Lemon Haze is a two-time Cannabis Cup winner that crosses Lemon Skunk with Super Silver Haze. This kief-caked multi-colored sativa delivers energetic, lively effects that are great for social occasions. Its zesty lemon aroma fills the room and the tangy flavors delight the palate.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "450-500g/m²",
    popularity: 76,
  },
  {
    name: "Cherry Pie",
    type: "Hybrid",
    ratio: "70% Indica / 30% Sativa",
    thcMin: 16, thcMax: 24, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Caryophyllene", "Pinene"],
    effects: ["Relaxed", "Happy", "Euphoric", "Uplifted", "Giggly"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Berry", "Sweet", "Earthy"],
    bestFor: ["Anxiety", "Pain", "Social"],
    description: "Cherry Pie is a hybrid cross of Granddaddy Purple and Durban Poison that delivers a balanced high with both cerebral stimulation and body relaxation. Its dense buds are reminiscent of actual cherry pie with a sweet and tart aroma. This strain is perfect for afternoon use when you want to unwind without full sedation.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 75,
  },
  {
    name: "Do-Si-Dos",
    type: "Indica",
    ratio: "70% Indica / 30% Sativa",
    thcMin: 19, thcMax: 30, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Caryophyllene", "Linalool"],
    effects: ["Relaxed", "Euphoric", "Happy", "Sleepy", "Tingly"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Sweet", "Earthy", "Floral"],
    bestFor: ["Pain", "Sleep", "Anxiety"],
    description: "Do-Si-Dos is an indica-dominant hybrid from Archive Seed Bank, crossing Girl Scout Cookies with Face Off OG. With its high THC content, this strain delivers a powerful body stone accompanied by a glassy-eyed euphoria. Its sweet minty and earthy flavor profile has made it a modern classic.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 74,
  },
  {
    name: "Mimosa",
    type: "Hybrid",
    ratio: "70% Sativa / 30% Indica",
    thcMin: 19, thcMax: 27, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Myrcene", "Caryophyllene"],
    effects: ["Happy", "Uplifted", "Energetic", "Creative", "Focused"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Citrus", "Tropical", "Sweet"],
    bestFor: ["Focus", "Social", "Creativity"],
    description: "Mimosa is a sativa-dominant hybrid born from crossing Clementine with Purple Punch. Named after the brunch cocktail, this strain delivers a similarly uplifting and bright experience. Its citrus-forward flavor profile and energizing effects make it an ideal morning or early afternoon strain.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 73,
  },
  {
    name: "MAC 1",
    type: "Hybrid",
    ratio: "50% Indica / 50% Sativa",
    thcMin: 20, thcMax: 23, cbdMin: 0, cbdMax: 0.2,
    terpenes: ["Limonene", "Caryophyllene", "Myrcene"],
    effects: ["Happy", "Uplifted", "Creative", "Euphoric", "Relaxed"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Citrus", "Diesel", "Sweet"],
    bestFor: ["Creativity", "Social", "Anxiety"],
    description: "MAC 1 (Miracle Alien Cookies) is a balanced hybrid from Capulator that crosses Alien Cookies F2 with Colombian and Starfighter. Known for its gorgeous frosted appearance and uplifting effects, MAC 1 delivers creative energy paired with body relaxation. Its sour citrus and diesel aroma is complex and inviting.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 72,
  },
  {
    name: "Ice Cream Cake",
    type: "Indica",
    ratio: "75% Indica / 25% Sativa",
    thcMin: 20, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Caryophyllene", "Linalool"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Calm"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Vanilla", "Sweet", "Earthy"],
    bestFor: ["Sleep", "Pain", "Anxiety"],
    description: "Ice Cream Cake is an indica-dominant cross of Wedding Cake and Gelato #33. This dessert strain delivers a creamy vanilla flavor with subtle nutty undertones. Its sedating effects make it perfect for evening use, melting away pain, insomnia, and anxiety with a blissful body high.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 71,
  },
  {
    name: "Cereal Milk",
    type: "Hybrid",
    ratio: "50% Indica / 50% Sativa",
    thcMin: 18, thcMax: 23, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Caryophyllene", "Myrcene"],
    effects: ["Happy", "Euphoric", "Relaxed", "Uplifted", "Focused"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Sweet", "Vanilla", "Berry"],
    bestFor: ["Social", "Creativity", "Anxiety"],
    description: "Cereal Milk is a balanced hybrid from Cookies that crosses Y Life with Snowman. Named for its flavor that resembles the sweet milk left after a bowl of fruity cereal, this strain delivers a balanced high that lifts your mood while keeping you relaxed. A modern dispensary staple.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 70,
  },
  {
    name: "Biscotti",
    type: "Indica",
    ratio: "80% Indica / 20% Sativa",
    thcMin: 21, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Caryophyllene", "Myrcene"],
    effects: ["Relaxed", "Euphoric", "Happy", "Sleepy", "Hungry"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Sweet", "Coffee", "Earthy"],
    bestFor: ["Pain", "Sleep", "Appetite"],
    description: "Biscotti is a heavy indica from Cookies that crosses Gelato #25 with South Florida OG. This potent strain delivers a sweet, cookie-like aroma with diesel undertones. Its sedating effects provide full-body relaxation and mental tranquility, making it ideal for evening unwinding.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 69,
  },
  {
    name: "Lemon Cherry Gelato",
    type: "Hybrid",
    ratio: "60% Indica / 40% Sativa",
    thcMin: 20, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Caryophyllene", "Myrcene"],
    effects: ["Relaxed", "Happy", "Euphoric", "Creative", "Tingly"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Citrus", "Berry", "Sweet"],
    bestFor: ["Pain", "Creativity", "Anxiety"],
    description: "Lemon Cherry Gelato is a flavorful hybrid combining Sunset Sherbet with Girl Scout Cookies. This strain has exploded in popularity for its incredible terpene profile delivering bright lemon and cherry flavors over a creamy gelato base. The effects are balanced between uplifting cerebral energy and soothing body relaxation.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 68,
  },
  {
    name: "Gary Payton",
    type: "Hybrid",
    ratio: "50% Indica / 50% Sativa",
    thcMin: 20, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Linalool"],
    effects: ["Euphoric", "Happy", "Relaxed", "Tingly", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Diesel", "Earthy", "Sweet"],
    bestFor: ["Social", "Creativity", "Pain"],
    description: "Gary Payton is a balanced hybrid from Cookies, created in collaboration with basketball legend Gary Payton. Crossing The Y with Snowman, this strain delivers a potent cerebral experience with a relaxing body buzz. Its rich diesel and earthy flavors are complemented by a sweet, smooth finish.",
    growDifficulty: "Difficult",
    floweringTime: "9-10 weeks",
    yieldIndoor: "300-350g/m²",
    popularity: 67,
  },
  {
    name: "London Pound Cake",
    type: "Indica",
    ratio: "70% Indica / 30% Sativa",
    thcMin: 22, thcMax: 29, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Limonene", "Caryophyllene", "Linalool"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Sweet", "Berry", "Earthy"],
    bestFor: ["Sleep", "Pain", "Appetite"],
    description: "London Pound Cake is a potent indica-leaning hybrid from Cookies. Known for its incredibly sweet, berry-forward flavor reminiscent of a berry pound cake, this strain delivers deeply relaxing effects. Its potent THC content makes it a heavy hitter for experienced users seeking full-body relaxation.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 66,
  },
  {
    name: "Jealousy",
    type: "Hybrid",
    ratio: "50% Indica / 50% Sativa",
    thcMin: 18, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    effects: ["Relaxed", "Happy", "Euphoric", "Tingly", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Earthy", "Sweet", "Diesel"],
    bestFor: ["Anxiety", "Pain", "Creativity"],
    description: "Jealousy is a balanced hybrid from Seed Junky Genetics that crosses Gelato 41 with Sherbet. This trendy strain has taken dispensaries by storm with its gassy, funky aroma and balanced effects. It delivers cerebral clarity paired with body relaxation, making it versatile for any time of day.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 65,
  },
  {
    name: "Pink Runtz",
    type: "Hybrid",
    ratio: "50% Indica / 50% Sativa",
    thcMin: 23, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Linalool"],
    effects: ["Euphoric", "Happy", "Relaxed", "Tingly", "Giggly"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Sweet", "Berry", "Tropical"],
    bestFor: ["Social", "Anxiety", "Pain"],
    description: "Pink Runtz is a balanced hybrid phenotype of the original Runtz strain, distinguished by its pink-hued buds and candy-like aroma. This strain delivers a euphoric, giggly high that transitions into a soothing body relaxation. Its sweet, fruity flavors make it incredibly enjoyable to consume.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 64,
  },
  {
    name: "Tropicana Cookies",
    type: "Sativa",
    ratio: "70% Sativa / 30% Indica",
    thcMin: 19, thcMax: 22, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Terpinolene", "Myrcene", "Caryophyllene"],
    effects: ["Energetic", "Happy", "Uplifted", "Creative", "Focused"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Citrus", "Tropical", "Sweet"],
    bestFor: ["Focus", "Creativity", "Social"],
    description: "Tropicana Cookies is a sativa-dominant hybrid that crosses Girl Scout Cookies with Tangie. This strain is known for its incredible purple-hued buds and potent citrus aroma. The effects are uplifting and energizing with a clear-headed focus that makes it perfect for daytime creative work.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 63,
  },
  {
    name: "GMO Cookies",
    type: "Indica",
    ratio: "90% Indica / 10% Sativa",
    thcMin: 24, thcMax: 30, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Diesel", "Earthy", "Coffee"],
    bestFor: ["Sleep", "Pain", "Appetite"],
    description: "GMO Cookies, also known as Garlic Cookies, is a potent indica-dominant hybrid that crosses Chemdawg with Girl Scout Cookies. Known for its pungent garlic, mushroom, and onion aroma (hence the name), this strain delivers an intensely relaxing body high with strong sedative effects.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "400-500g/m²",
    popularity: 62,
  },
  {
    name: "Purple Punch",
    type: "Indica",
    ratio: "90% Indica / 10% Sativa",
    thcMin: 18, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Pinene"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Calm"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Grape", "Berry", "Sweet"],
    bestFor: ["Sleep", "Pain", "Anxiety"],
    description: "Purple Punch is a delicious indica cross of Larry OG and Granddaddy Purple. It delivers a one-two combo of cerebral euphoria and physical relaxation. Its grape candy and blueberry muffin flavors make it taste as good as it smells. A perfect dessert strain for ending your day on a high note.",
    growDifficulty: "Easy",
    floweringTime: "7-8 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 61,
  },
  {
    name: "Slurricane",
    type: "Indica",
    ratio: "70% Indica / 30% Sativa",
    thcMin: 20, thcMax: 28, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Calm"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Berry", "Sweet", "Grape"],
    bestFor: ["Sleep", "Pain", "Anxiety"],
    description: "Slurricane is a potent indica-dominant hybrid from In House Genetics, crossing Do-Si-Dos with Purple Punch. This strain delivers a knockout punch of relaxation with a sweet berry flavor profile. Its heavy sedating effects make it an excellent choice for experienced users seeking deep relaxation and sleep.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 60,
  },
  {
    name: "Sundae Driver",
    type: "Hybrid",
    ratio: "50% Indica / 50% Sativa",
    thcMin: 16, thcMax: 24, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Humulene"],
    effects: ["Relaxed", "Happy", "Euphoric", "Creative", "Calm"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Sweet", "Berry", "Earthy"],
    bestFor: ["Anxiety", "Pain", "Creativity"],
    description: "Sundae Driver is a balanced hybrid from Cannarado Genetics, crossing FPOG with Grape Pie. This strain delivers a smooth, creamy experience with sweet chocolate and grape flavors. Its balanced effects produce a calm, happy state that is equally suited for social occasions or solo relaxation.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 59,
  },
  {
    name: "Banana Kush",
    type: "Indica",
    ratio: "60% Indica / 40% Sativa",
    thcMin: 18, thcMax: 25, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Limonene", "Caryophyllene"],
    effects: ["Relaxed", "Happy", "Euphoric", "Uplifted", "Sleepy"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Sweet", "Tropical", "Earthy"],
    bestFor: ["Anxiety", "Pain", "Sleep"],
    description: "Banana Kush is a popular indica-dominant hybrid that crosses Ghost OG with Skunk Haze. True to its name, this strain delivers a sweet tropical banana flavor with hints of earthy vanilla. The effects build gradually into a mellow, happy relaxation that eases both mind and body.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 58,
  },
  {
    name: "Tangie",
    type: "Sativa",
    ratio: "70% Sativa / 30% Indica",
    thcMin: 19, thcMax: 22, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Limonene", "Pinene"],
    effects: ["Happy", "Uplifted", "Energetic", "Euphoric", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Citrus", "Sweet", "Tropical"],
    bestFor: ["Focus", "Creativity", "Social"],
    description: "Tangie is a sativa-dominant hybrid that reimagines the classic Tangerine Dream. Crossing California Orange with Skunk, this Amsterdam-born strain delivers an unmistakable citrus aroma. Its uplifting, creative effects paired with a sharp tangerine flavor make it a refreshing daytime choice.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 57,
  },
  {
    name: "LA Confidential",
    type: "Indica",
    ratio: "95% Indica / 5% Sativa",
    thcMin: 16, thcMax: 25, cbdMin: 0, cbdMax: 0.3,
    terpenes: ["Myrcene", "Limonene", "Caryophyllene"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Calm"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Pine", "Earthy", "Skunky"],
    bestFor: ["Sleep", "Pain", "Anxiety"],
    description: "LA Confidential is a classic indica bred from OG LA Affie and Afghani. This award-winning strain delivers fast-acting relaxation with a smooth pine and earthy flavor. Its psychedelic visual effects and deeply calming body stone make it a top choice for nighttime use and pain management.",
    growDifficulty: "Easy",
    floweringTime: "7-8 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 56,
  },
  {
    name: "Maui Wowie",
    type: "Sativa",
    ratio: "80% Sativa / 20% Indica",
    thcMin: 13, thcMax: 20, cbdMin: 0, cbdMax: 0.3,
    terpenes: ["Myrcene", "Pinene", "Limonene"],
    effects: ["Happy", "Uplifted", "Energetic", "Euphoric", "Creative"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Tropical", "Citrus", "Sweet"],
    bestFor: ["Social", "Creativity", "Focus"],
    description: "Maui Wowie is a classic sativa that originated on the volcanic soils of Hawaii. This legendary strain delivers tropical flavors with a piney fresh aroma. Its lightweight effects provide a mellow, energetic buzz that keeps you productive and creative throughout the day without overwhelming potency.",
    growDifficulty: "Easy",
    floweringTime: "9-11 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 55,
  },
  {
    name: "Hindu Kush",
    type: "Indica",
    ratio: "100% Indica",
    thcMin: 15, thcMax: 20, cbdMin: 0.1, cbdMax: 0.3,
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Calm"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Earthy", "Sweet", "Pine"],
    bestFor: ["Sleep", "Pain", "Anxiety"],
    description: "Hindu Kush is a pure indica landrace strain named after the mountain range stretching across Afghanistan and Pakistan. This ancient strain has evolved to produce a thick protective coat of crystal trichomes. Its subtle sweet and earthy sandalwood aroma delivers a deeply calming and meditative body high.",
    growDifficulty: "Easy",
    floweringTime: "7-8 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 54,
  },
  {
    name: "Afghan Kush",
    type: "Indica",
    ratio: "100% Indica",
    thcMin: 17, thcMax: 21, cbdMin: 0.1, cbdMax: 0.6,
    terpenes: ["Myrcene", "Pinene", "Caryophyllene"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Earthy", "Herbal", "Pine"],
    bestFor: ["Sleep", "Pain", "Appetite"],
    description: "Afghan Kush is a heavy indica landrace originating near the Afghan-Pakistani border where the earliest cannabis strains were cultivated. This pure indica delivers deeply sedating effects perfect for nighttime use. Its earthy, herbal aroma with hints of hash transports you to the mountains of the Hindu Kush.",
    growDifficulty: "Easy",
    floweringTime: "7-8 weeks",
    yieldIndoor: "400-450g/m²",
    popularity: 53,
  },
  {
    name: "Bruce Banner",
    type: "Hybrid",
    ratio: "60% Sativa / 40% Indica",
    thcMin: 24, thcMax: 30, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Myrcene", "Caryophyllene", "Limonene"],
    effects: ["Euphoric", "Happy", "Creative", "Energetic", "Relaxed"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Paranoia"],
    flavors: ["Diesel", "Sweet", "Earthy"],
    bestFor: ["Creativity", "Pain", "Social"],
    description: "Named after the Incredible Hulk's alter ego, Bruce Banner is a potent hybrid that packs a powerful punch. Crossing OG Kush with Strawberry Diesel, this strain delivers a knockout combination of euphoria and creativity. Its sweet, diesel aroma gives way to a smooth, balanced experience for experienced users.",
    growDifficulty: "Moderate",
    floweringTime: "8-10 weeks",
    yieldIndoor: "450-500g/m²",
    popularity: 52,
  },
  {
    name: "Headband",
    type: "Hybrid",
    ratio: "60% Indica / 40% Sativa",
    thcMin: 20, thcMax: 27, cbdMin: 0, cbdMax: 0.2,
    terpenes: ["Myrcene", "Limonene", "Caryophyllene"],
    effects: ["Relaxed", "Happy", "Euphoric", "Creative", "Focused"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Dizzy"],
    flavors: ["Earthy", "Diesel", "Citrus"],
    bestFor: ["Pain", "Creativity", "Anxiety"],
    description: "Headband gets its name from the slight pressure it creates around the crown of your head, like wearing a headband. This potent hybrid crosses OG Kush with Sour Diesel, delivering a creeping high that builds into a full-body experience. Its earthy and diesel flavors are smooth and satisfying.",
    growDifficulty: "Moderate",
    floweringTime: "9-10 weeks",
    yieldIndoor: "350-450g/m²",
    popularity: 51,
  },
  {
    name: "King Louis XIII",
    type: "Indica",
    ratio: "70% Indica / 30% Sativa",
    thcMin: 20, thcMax: 28, cbdMin: 0, cbdMax: 0.2,
    terpenes: ["Myrcene", "Limonene", "Pinene"],
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    negativeEffects: ["Dry mouth", "Dry eyes", "Couch-lock"],
    flavors: ["Pine", "Earthy", "Skunky"],
    bestFor: ["Sleep", "Pain", "Appetite"],
    description: "King Louis XIII is a potent indica-dominant strain named after the French king. This OG Kush phenotype delivers a royal knockout with deeply relaxing effects that melt away pain and insomnia. Its piney, earthy aroma with skunky undertones announces a powerful sedating experience best reserved for evenings.",
    growDifficulty: "Moderate",
    floweringTime: "8-9 weeks",
    yieldIndoor: "350-400g/m²",
    popularity: 50,
  },
  {
    name: "Animal Mints",
    type: "Hybrid",
    ratio: "50% Indica / 50% Sativa",
    thcMin: 22, thcMax: 32, cbdMin: 0, cbdMax: 0.1,
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    effects: ["Relaxed", "Euphoric", "Happy", "Creative", "Tingly"],
    negativeEffects: ["Dry mouth", "Dry eyes"],
    flavors: ["Mint", "Sweet", "Diesel"],
    bestFor: ["Pain", "Anxiety", "Creativity"],
    description: "Animal Mints is a potent balanced hybrid from Seed Junky Genetics, crossing Animal Cookies with SinMint Cookies. This high-THC strain delivers a complex minty flavor with cookie dough undertones. Its effects build from an initial cerebral uplift into deep body relaxation, perfect for experienced consumers.",
    growDifficulty: "Difficult",
    floweringTime: "8-9 weeks",
    yieldIndoor: "300-350g/m²",
    popularity: 49,
  },
];
