export interface GlossaryTerm {
  term: string;
  slug: string;
  definition: string;
  expandedExplanation: string;
  category: string;
  relatedTerms: string[];
}

export const glossaryTerms: GlossaryTerm[] = [
  { term: "Cannabinoid", slug: "cannabinoid", definition: "A chemical compound found in the cannabis plant that interacts with the body's endocannabinoid system.", expandedExplanation: "The two most well-known cannabinoids are THC (psychoactive) and CBD (non-psychoactive). Over 100 cannabinoids have been identified in cannabis.", category: "Cannabinoids", relatedTerms: ["THC", "CBD", "Endocannabinoid System"] },
  { term: "THC", slug: "thc", definition: "Tetrahydrocannabinol, the primary psychoactive compound in cannabis responsible for the 'high' sensation.", expandedExplanation: "THC binds to CB1 receptors in the brain, producing euphoria, relaxation, altered perception, and increased appetite. Typical flower THC content ranges from 10% to 30%.", category: "Cannabinoids", relatedTerms: ["Cannabinoid", "CBD", "THCA"] },
  { term: "CBD", slug: "cbd", definition: "Cannabidiol, a non-psychoactive cannabinoid used for pain, anxiety, inflammation, and seizure disorders.", expandedExplanation: "CBD does not produce a high and may actually moderate the effects of THC. It has been FDA-approved in the form of Epidiolex for treating certain types of epilepsy.", category: "Cannabinoids", relatedTerms: ["Cannabinoid", "THC", "Hemp"] },
  { term: "CBN", slug: "cbn", definition: "Cannabinol, a mildly psychoactive cannabinoid formed when THC ages and oxidizes.", expandedExplanation: "CBN is often associated with sedative effects and is commonly marketed in sleep-aid products, though research on its sedative properties is still limited.", category: "Cannabinoids", relatedTerms: ["Cannabinoid", "THC"] },
  { term: "CBG", slug: "cbg", definition: "Cannabigerol, a non-psychoactive cannabinoid often called the 'mother cannabinoid' because other cannabinoids are synthesized from it.", expandedExplanation: "CBG is found in small quantities in most cannabis strains. Early research suggests potential benefits for inflammation, pain, and nausea.", category: "Cannabinoids", relatedTerms: ["Cannabinoid", "CBD"] },
  { term: "THCA", slug: "thca", definition: "Tetrahydrocannabinolic acid, the non-psychoactive precursor to THC found in raw cannabis.", expandedExplanation: "THCA converts to THC through decarboxylation (heating). Raw cannabis juice and tinctures contain THCA, which may have anti-inflammatory properties without producing a high.", category: "Cannabinoids", relatedTerms: ["THC", "Decarboxylation"] },
  { term: "Terpene", slug: "terpene", definition: "Aromatic compounds found in cannabis and many other plants that influence smell, taste, and effects.", expandedExplanation: "Common cannabis terpenes include myrcene, limonene, caryophyllene, pinene, and linalool. Terpenes contribute to the entourage effect and help differentiate strain experiences.", category: "Science", relatedTerms: ["Entourage Effect", "Myrcene", "Limonene"] },
  { term: "Entourage Effect", slug: "entourage-effect", definition: "The theory that cannabis compounds work better together than in isolation.", expandedExplanation: "When cannabinoids, terpenes, and flavonoids are consumed together, they may produce enhanced or modified effects compared to isolated compounds. This is why full-spectrum products are often preferred over isolates.", category: "Science", relatedTerms: ["Terpene", "Cannabinoid", "Full-Spectrum"] },
  { term: "Endocannabinoid System", slug: "endocannabinoid-system", definition: "A biological system in the human body consisting of endocannabinoids, receptors, and enzymes that regulates various physiological processes.", expandedExplanation: "The ECS includes CB1 receptors (primarily in the brain) and CB2 receptors (primarily in the immune system). It helps regulate mood, pain, appetite, sleep, and immune function.", category: "Science", relatedTerms: ["Cannabinoid", "CB1", "CB2"] },
  { term: "Decarboxylation", slug: "decarboxylation", definition: "The chemical process of applying heat to cannabis to activate its cannabinoids.", expandedExplanation: "Raw cannabis contains THCA, which must be decarboxylated (heated) to become the psychoactive THC. This happens automatically when smoking or vaping, but must be done intentionally when making edibles.", category: "Science", relatedTerms: ["THCA", "THC", "Edible"] },
  { term: "Indica", slug: "indica", definition: "A cannabis subspecies traditionally associated with relaxing, sedating, and body-focused effects.", expandedExplanation: "Indica plants are typically shorter and bushier with wider leaves. While the indica/sativa distinction is debated in modern cannabis science, indica-labeled products are generally marketed for nighttime use and relaxation.", category: "Consumption", relatedTerms: ["Sativa", "Hybrid", "Strain"] },
  { term: "Sativa", slug: "sativa", definition: "A cannabis subspecies traditionally associated with energizing, uplifting, and cerebral effects.", expandedExplanation: "Sativa plants tend to be taller with narrow leaves and longer flowering times. Sativa-labeled products are typically marketed for daytime use, creativity, and social activities.", category: "Consumption", relatedTerms: ["Indica", "Hybrid", "Strain"] },
  { term: "Hybrid", slug: "hybrid", definition: "A cannabis strain created by crossbreeding indica and sativa genetics.", expandedExplanation: "Most modern cannabis strains are hybrids. They are often described as indica-dominant, sativa-dominant, or balanced, depending on their genetic lineage and effects profile.", category: "Consumption", relatedTerms: ["Indica", "Sativa", "Strain"] },
  { term: "Strain", slug: "strain", definition: "A specific variety of cannabis with a distinct genetic profile, appearance, and effect profile.", expandedExplanation: "Strains (increasingly called 'cultivars') are bred to produce specific cannabinoid and terpene profiles. Popular strains include Blue Dream, OG Kush, and Girl Scout Cookies.", category: "Consumption", relatedTerms: ["Indica", "Sativa", "Hybrid", "Cultivar"] },
  { term: "Edible", slug: "edible", definition: "A food or drink product infused with cannabis extract, typically THC or CBD.", expandedExplanation: "Edibles are processed by the liver, converting THC to 11-hydroxy-THC, which is more potent and longer-lasting than inhaled THC. Effects typically begin 30-90 minutes after consumption and can last 4-8 hours.", category: "Consumption", relatedTerms: ["Decarboxylation", "THC", "Microdose"] },
  { term: "Tincture", slug: "tincture", definition: "A liquid cannabis extract, usually alcohol or oil-based, taken sublingually (under the tongue).", expandedExplanation: "Tinctures offer precise dosing through a dropper and faster onset than edibles (15-30 minutes when taken sublingually). They can also be added to food or drinks.", category: "Consumption", relatedTerms: ["Edible", "CBD", "THC"] },
  { term: "Concentrate", slug: "concentrate", definition: "A highly potent cannabis extract with THC levels typically ranging from 60% to 99%.", expandedExplanation: "Concentrates include wax, shatter, budder, live resin, and rosin. They are consumed through dabbing or vaporizing and are significantly more potent than flower.", category: "Consumption", relatedTerms: ["Dab", "Live Resin", "Rosin"] },
  { term: "Dab", slug: "dab", definition: "A method of consuming cannabis concentrates by vaporizing them on a heated surface.", expandedExplanation: "Dabbing uses a 'dab rig' (similar to a bong) with a heated nail or banger. It produces intense, fast-acting effects and is recommended only for experienced users due to high potency.", category: "Consumption", relatedTerms: ["Concentrate", "Live Resin"] },
  { term: "Microdose", slug: "microdose", definition: "Taking a very small amount of cannabis, typically 1-2.5mg of THC, to achieve subtle therapeutic effects without a full high.", expandedExplanation: "Microdosing is popular among professionals and medical patients who want benefits like stress relief or focus enhancement without impairment. It can be done with edibles, tinctures, or low-dose vaporizers.", category: "Consumption", relatedTerms: ["Edible", "THC", "Tolerance"] },
  { term: "Tolerance", slug: "tolerance", definition: "The body's reduced response to cannabis after repeated use, requiring higher doses to achieve the same effects.", expandedExplanation: "Cannabis tolerance develops primarily through downregulation of CB1 receptors. A tolerance break (T-break) of 2-4 weeks can significantly reset tolerance. Regular users may notice tolerance building within days to weeks.", category: "Science", relatedTerms: ["Tolerance Break", "CB1", "Endocannabinoid System"] },
  { term: "Tolerance Break", slug: "tolerance-break", definition: "A period of abstinence from cannabis intended to reset the body's tolerance to cannabinoids.", expandedExplanation: "Research shows CB1 receptors begin recovering within 48 hours. A 21-30 day break is considered sufficient for a near-complete tolerance reset. Symptoms during a T-break may include irritability, insomnia, and decreased appetite.", category: "Science", relatedTerms: ["Tolerance", "CB1"] },
  { term: "Trichome", slug: "trichome", definition: "Tiny, crystal-like structures on cannabis flowers that produce and contain cannabinoids and terpenes.", expandedExplanation: "Trichome density and color are indicators of potency and harvest readiness. Clear trichomes indicate early harvest, milky trichomes indicate peak THC, and amber trichomes indicate higher CBN and sedative effects.", category: "Growing", relatedTerms: ["Cannabinoid", "Terpene", "Harvest"] },
  { term: "Cola", slug: "cola", definition: "The flowering top of a female cannabis plant, also known as the bud site.", expandedExplanation: "The main cola grows at the top of the plant, while smaller colas develop at branch tips. Training techniques like topping and LST can create multiple large colas, increasing yield.", category: "Growing", relatedTerms: ["Bud", "Topping", "LST"] },
  { term: "Curing", slug: "curing", definition: "The process of slowly drying harvested cannabis in controlled conditions to improve flavor, potency, and smoothness.", expandedExplanation: "Proper curing involves drying buds for 5-10 days, then storing them in airtight jars for 2-8 weeks with daily burping. Well-cured cannabis is smoother to smoke and has a more complex terpene profile.", category: "Growing", relatedTerms: ["Harvest", "Trichome", "Terpene"] },
  { term: "Autoflower", slug: "autoflower", definition: "A cannabis variety that flowers automatically based on age rather than changes in light cycle.", expandedExplanation: "Autoflowering strains contain Cannabis ruderalis genetics and typically finish in 8-12 weeks from seed. They are popular with beginners because they require no light schedule changes and are generally smaller and more forgiving.", category: "Growing", relatedTerms: ["Photoperiod", "Ruderalis", "Flowering"] },
  { term: "Photoperiod", slug: "photoperiod", definition: "A cannabis plant that requires specific light/dark cycles to trigger flowering, typically 12 hours of darkness.", expandedExplanation: "Photoperiod plants remain in vegetative growth under 18+ hours of light and begin flowering when switched to 12/12. They generally produce larger yields than autoflowers and allow for longer vegetative growth.", category: "Growing", relatedTerms: ["Autoflower", "Flowering", "Vegetative"] },
  { term: "LST", slug: "lst", definition: "Low Stress Training, a technique of gently bending and tying cannabis stems to create an even canopy.", expandedExplanation: "LST exposes more bud sites to light, increasing yield without stressing the plant. It is beginner-friendly and can be combined with other training methods like topping or scrogging.", category: "Growing", relatedTerms: ["Topping", "ScrOG", "Cola"] },
  { term: "Dispensary", slug: "dispensary", definition: "A licensed retail location where cannabis products are legally sold to consumers.", expandedExplanation: "Dispensaries may be medical-only, recreational-only, or dual-license. They typically require valid ID (21+ for recreational, 18+ with medical card), and many offer consultation with knowledgeable budtenders.", category: "Legal", relatedTerms: ["Budtender", "Medical Card"] },
  { term: "Medical Card", slug: "medical-card", definition: "A state-issued identification card that allows patients to purchase cannabis from medical dispensaries.", expandedExplanation: "Requirements vary by state but typically include a qualifying medical condition and a recommendation from a licensed physician. Medical card holders often receive tax benefits, higher possession limits, and access to higher-potency products.", category: "Legal", relatedTerms: ["Dispensary", "Qualifying Condition"] },
  { term: "Decriminalization", slug: "decriminalization", definition: "A policy change that reduces cannabis possession penalties from criminal charges to civil fines or no penalty.", expandedExplanation: "Decriminalization does not make cannabis legal and does not create a regulated market. Possession may still result in a fine, and cultivation and sales typically remain illegal. It is considered a step between prohibition and full legalization.", category: "Legal", relatedTerms: ["Legalization", "Prohibition"] },
  { term: "Hemp", slug: "hemp", definition: "Cannabis sativa plants containing 0.3% THC or less by dry weight, federally legal in the United States since 2018.", expandedExplanation: "The 2018 Farm Bill legalized hemp cultivation and hemp-derived products including CBD. Hemp is used for fiber, seeds, CBD extraction, and industrial applications. Products derived from hemp are legal in all 50 states.", category: "Legal", relatedTerms: ["CBD", "Farm Bill"] },
  { term: "Full-Spectrum", slug: "full-spectrum", definition: "A cannabis extract containing the full range of cannabinoids, terpenes, and other compounds naturally present in the plant.", expandedExplanation: "Full-spectrum products leverage the entourage effect, potentially providing greater therapeutic benefits than isolated compounds. They may contain trace amounts of THC (up to 0.3% in hemp-derived products).", category: "Medical", relatedTerms: ["Entourage Effect", "Broad-Spectrum", "Isolate"] },
  { term: "Broad-Spectrum", slug: "broad-spectrum", definition: "A cannabis extract containing multiple cannabinoids and terpenes but with THC completely removed.", expandedExplanation: "Broad-spectrum products offer some entourage effect benefits without any risk of THC exposure. They are a middle ground between full-spectrum and isolate products, popular with users who want to avoid THC entirely.", category: "Medical", relatedTerms: ["Full-Spectrum", "Isolate", "THC"] },
  { term: "Isolate", slug: "isolate", definition: "A pure, crystalline form of a single cannabinoid, typically CBD or THC, with all other compounds removed.", expandedExplanation: "CBD isolate is 99%+ pure CBD with no THC, terpenes, or other cannabinoids. It is the best option for users who need to avoid THC entirely, such as those subject to drug testing.", category: "Medical", relatedTerms: ["Full-Spectrum", "Broad-Spectrum", "CBD"] },
  { term: "Topical", slug: "topical", definition: "A cannabis-infused product applied directly to the skin for localized relief without psychoactive effects.", expandedExplanation: "Topicals include lotions, balms, salves, and transdermal patches. They are used for localized pain, inflammation, and skin conditions. Most topicals do not enter the bloodstream and therefore do not produce a high.", category: "Consumption", relatedTerms: ["CBD", "THC", "Transdermal"] },
  { term: "Live Resin", slug: "live-resin", definition: "A cannabis concentrate made from fresh-frozen plant material, preserving the full terpene profile.", expandedExplanation: "Unlike extracts made from dried and cured cannabis, live resin captures terpenes that would otherwise evaporate during drying. This results in a more flavorful and aromatic product with effects closer to the living plant.", category: "Consumption", relatedTerms: ["Concentrate", "Terpene", "Dab"] },
  { term: "Rosin", slug: "rosin", definition: "A solventless cannabis concentrate made by applying heat and pressure to flower or hash.", expandedExplanation: "Rosin is considered one of the cleanest concentrate forms because it uses no chemical solvents. It can be made at home with a hair straightener and parchment paper, though commercial rosin presses produce higher quality results.", category: "Consumption", relatedTerms: ["Concentrate", "Solventless"] },
  { term: "Budtender", slug: "budtender", definition: "A dispensary employee who assists customers with cannabis product selection and provides consumption guidance.", expandedExplanation: "Good budtenders have knowledge of strain profiles, consumption methods, dosing, and local regulations. They can help match products to individual needs and preferences, similar to a sommelier for wine.", category: "Legal", relatedTerms: ["Dispensary", "Strain"] },
  { term: "Myrcene", slug: "myrcene", definition: "The most common terpene in cannabis, known for its earthy, musky aroma and relaxing, sedating effects.", expandedExplanation: "Myrcene is also found in mangoes, lemongrass, and hops. It may enhance THC absorption and is associated with the 'couch-lock' effect of some indica strains. Strains with more than 0.5% myrcene are often more sedating.", category: "Science", relatedTerms: ["Terpene", "Indica", "Entourage Effect"] },
  { term: "Limonene", slug: "limonene", definition: "A citrus-scented terpene associated with mood elevation, stress relief, and anti-anxiety effects.", expandedExplanation: "Limonene is abundant in citrus fruit peels and is one of the most common terpenes in cannabis. It may have anti-inflammatory and antifungal properties and is associated with uplifting, energetic strain effects.", category: "Science", relatedTerms: ["Terpene", "Sativa"] },
  { term: "Caryophyllene", slug: "caryophyllene", definition: "A spicy, peppery terpene that uniquely binds to CB2 receptors, making it both a terpene and a dietary cannabinoid.", expandedExplanation: "Caryophyllene is found in black pepper, cloves, and cinnamon. Its ability to interact directly with the endocannabinoid system may provide anti-inflammatory and pain-relieving effects without psychoactivity.", category: "Science", relatedTerms: ["Terpene", "CB2", "Endocannabinoid System"] },
];
