export interface SeedStateLaw {
  state: string;
  abbreviation: string;
  legalStatus: "Fully Legal" | "Medical Only" | "Decriminalized" | "Illegal";
  recreationalLegal: boolean;
  medicalLegal: boolean;
  possessionLimitRec: string;
  possessionLimitMed: string;
  ageRequirement: number;
  homeGrowAllowed: boolean;
  homeGrowLimit: string;
  purchaseLocations: "Dispensaries" | "Delivery Only" | "Both" | "N/A";
  publicConsumption: string;
  recentChanges: string;
  regulatoryUrl: string;
}

export const seedStateLaws: SeedStateLaw[] = [
  // ─── FULLY LEGAL (Recreational + Medical) ─────────────────────────────────────
  {
    state: "Alaska",
    abbreviation: "AK",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g",
    possessionLimitMed: "1 oz / 28g",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per adult, 3 mature; 12 per household",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; allowed in private residences and licensed on-site consumption areas",
    recentChanges: "Onsite consumption endorsements expanded in 2024; social equity licensing provisions updated",
    regulatoryUrl: "https://www.commerce.alaska.gov/web/amco/",
  },
  {
    state: "Arizona",
    abbreviation: "AZ",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g (5g max concentrate)",
    possessionLimitMed: "2.5 oz / 70g per 14-day period",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per person; 12 per household with 2+ adults",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public places; only in private residences or licensed establishments",
    recentChanges: "Prop 207 (Smart and Safe Act) fully implemented; social equity program licenses issued in 2023-2024",
    regulatoryUrl: "https://azdhs.gov/licensing/marijuana/index.php",
  },
  {
    state: "California",
    abbreviation: "CA",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28.5g flower; 8g concentrate",
    possessionLimitMed: "8 oz / 227g flower (with recommendation)",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per residence",
    purchaseLocations: "Both",
    publicConsumption: "Prohibited where tobacco smoking is banned; no consumption in public or within 1,000 ft of schools/daycares",
    recentChanges: "AB 1646 (2024) streamlined cannabis café licensing; ongoing local equity programs; interstate commerce pilot authorized under SB 1326",
    regulatoryUrl: "https://cannabis.ca.gov/",
  },
  {
    state: "Colorado",
    abbreviation: "CO",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "2 oz / 56g",
    possessionLimitMed: "2 oz / 56g (higher with extended plant count)",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per adult, 3 flowering; 12 per household",
    purchaseLocations: "Both",
    publicConsumption: "Prohibited in public; hospitality program allows licensed consumption lounges",
    recentChanges: "HB 23-1021 established hospitality and consumption lounges; delivery services fully operational statewide",
    regulatoryUrl: "https://sbg.colorado.gov/med",
  },
  {
    state: "Connecticut",
    abbreviation: "CT",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1.5 oz / 42.5g on person; 5 oz at home",
    possessionLimitMed: "5 oz / 142g per month",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per adult (3 mature); 12 per household",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in most public places; consumption only in private residences",
    recentChanges: "Home cultivation became legal October 2023; retail adult-use sales began January 2023; social equity applicant licensing ongoing",
    regulatoryUrl: "https://portal.ct.gov/dcp/license-services-division/drug-control/marijuana-program",
  },
  {
    state: "Delaware",
    abbreviation: "DE",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g",
    possessionLimitMed: "6 oz / 170g per month",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; private use only",
    recentChanges: "HB 1 and HB 2 signed in 2023 legalizing adult use; Marijuana Commissioner appointed; retail sales anticipated in 2025",
    regulatoryUrl: "https://dhss.delaware.gov/dhss/dph/hsp/medmarhome.html",
  },
  {
    state: "Hawaii",
    abbreviation: "HI",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g",
    possessionLimitMed: "4 oz / 113g",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per adult (medical: 10 plants per patient)",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public places; private residence use only",
    recentChanges: "SB 3335 signed 2024 legalizing recreational cannabis; retail framework under development for 2025-2026 launch",
    regulatoryUrl: "https://health.hawaii.gov/medicalcannabis/",
  },
  {
    state: "Illinois",
    abbreviation: "IL",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 30g flower; 5g concentrate; 500mg THC edibles",
    possessionLimitMed: "2.5 oz / 71g per 14-day period",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "5 plants per household (medical patients only; recreational home grow enacted 2025)",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; only in private residences or licensed consumption lounges",
    recentChanges: "Social equity licensing expanded; craft grower licenses issued in 2024; recreational home grow provision signed 2025",
    regulatoryUrl: "https://idfpr.illinois.gov/profs/adultusecan.asp",
  },
  {
    state: "Maine",
    abbreviation: "ME",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "2.5 oz / 71g",
    possessionLimitMed: "2.5 oz / 71g",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "3 mature plants, 12 immature plants per person",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; permitted in private residences",
    recentChanges: "Adult-use market matured; ongoing social equity discussions; delivery licensing expanded",
    regulatoryUrl: "https://www.maine.gov/dafs/ocp/",
  },
  {
    state: "Maryland",
    abbreviation: "MD",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1.5 oz / 42.5g flower; 12g concentrate",
    possessionLimitMed: "4 oz / 120g per 30-day period",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "2 plants per person",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; private consumption only",
    recentChanges: "Adult-use retail sales began July 2023; social equity licensing and expungement provisions ongoing",
    regulatoryUrl: "https://mmcc.maryland.gov/",
  },
  {
    state: "Massachusetts",
    abbreviation: "MA",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g on person; 10 oz at home",
    possessionLimitMed: "10 oz / 283g (60-day supply)",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per adult; 12 per household",
    purchaseLocations: "Both",
    publicConsumption: "Prohibited in public places; private residence only",
    recentChanges: "Cannabis Control Commission restructured in 2024; delivery operator equity programs expanded; consumption lounge regulations finalized",
    regulatoryUrl: "https://masscannabiscontrol.com/",
  },
  {
    state: "Michigan",
    abbreviation: "MI",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "2.5 oz / 71g on person; 10 oz at home",
    possessionLimitMed: "2.5 oz / 71g",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "12 plants per household",
    purchaseLocations: "Both",
    publicConsumption: "Prohibited in public; private property only",
    recentChanges: "Cannabis regulatory agency restructured; social equity program ongoing; consumption lounges under municipal approval",
    regulatoryUrl: "https://www.michigan.gov/cra",
  },
  {
    state: "Minnesota",
    abbreviation: "MN",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "2 oz / 56g in public; 2 lbs at home",
    possessionLimitMed: "2.5 oz / 71g per 30 days",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "8 plants per household, 4 mature",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; private use only",
    recentChanges: "HF 100 signed May 2023 legalizing adult use; Office of Cannabis Management established; retail sales began 2025",
    regulatoryUrl: "https://mn.gov/ocm/",
  },
  {
    state: "Missouri",
    abbreviation: "MO",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "3 oz / 85g",
    possessionLimitMed: "6 oz / 170g per 30 days",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 flowering plants, 6 non-flowering, 6 clones per person",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; consumption in private residences only",
    recentChanges: "Amendment 3 passed Nov 2022; adult-use sales began Feb 2023; expungement of prior convictions ongoing",
    regulatoryUrl: "https://health.mo.gov/safety/cannabis/",
  },
  {
    state: "Montana",
    abbreviation: "MT",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g",
    possessionLimitMed: "1 oz / 28g (5 oz for certain conditions)",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "4 mature plants, 4 seedlings per person",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public places; private property only",
    recentChanges: "I-190 fully implemented; local opt-out provisions remain; tax revenue allocation updated in 2024",
    regulatoryUrl: "https://mtrevenue.gov/cannabis/",
  },
  {
    state: "Nevada",
    abbreviation: "NV",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g flower; 3.5g concentrate",
    possessionLimitMed: "2.5 oz / 71g per 14 days",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per person; 12 per household (only if 25+ miles from dispensary, unless medical)",
    purchaseLocations: "Both",
    publicConsumption: "Prohibited in public; cannabis consumption lounges permitted under AB 341",
    recentChanges: "AB 341 consumption lounge licensing operational; social equity licenses issued; delivery expanded statewide",
    regulatoryUrl: "https://ccb.nv.gov/",
  },
  {
    state: "New Jersey",
    abbreviation: "NJ",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g",
    possessionLimitMed: "3 oz / 85g per 30 days",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; consumption only in private residences",
    recentChanges: "Adult-use market expanded with new dispensary licenses in 2024; delivery licensing in progress; no home grow provision",
    regulatoryUrl: "https://www.nj.gov/cannabis/",
  },
  {
    state: "New Mexico",
    abbreviation: "NM",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "2 oz / 56g",
    possessionLimitMed: "12 oz / 340g per 90 days (adequate supply)",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 mature plants, 18 immature per person; 12 mature per household",
    purchaseLocations: "Both",
    publicConsumption: "Prohibited in public; private consumption only; cannabis consumption areas authorized",
    recentChanges: "Cannabis Regulation Act fully implemented; micro-business licenses prioritized for equity; consumption area permits issued",
    regulatoryUrl: "https://www.rld.nm.gov/cannabis/",
  },
  {
    state: "New York",
    abbreviation: "NY",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "3 oz / 85g flower; 24g concentrate",
    possessionLimitMed: "60-day supply as determined by practitioner",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per person (3 mature); 12 per household",
    purchaseLocations: "Both",
    publicConsumption: "Allowed where tobacco smoking is permitted; not in vehicles, schools, or workplaces",
    recentChanges: "CAURD licensing program expanded; home cultivation authorized beginning 2025; illicit market enforcement increased",
    regulatoryUrl: "https://cannabis.ny.gov/",
  },
  {
    state: "Ohio",
    abbreviation: "OH",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "2.5 oz / 71g flower; 15g concentrate",
    possessionLimitMed: "2.5 oz / 71g per 90 days",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per person; 12 per household",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; private property only",
    recentChanges: "Issue 2 passed Nov 2023 legalizing adult use; Division of Cannabis Control establishing retail framework; adult-use sales began 2024",
    regulatoryUrl: "https://www.com.ohio.gov/cannabis",
  },
  {
    state: "Oregon",
    abbreviation: "OR",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g in public; 8 oz at home",
    possessionLimitMed: "24 oz / 680g",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "4 plants per household",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public places; private property only",
    recentChanges: "Psilocybin and cannabis regulatory updates in 2024; OLCC restructured into Oregon Liquor and Cannabis Commission; ongoing surplus management",
    regulatoryUrl: "https://www.oregon.gov/olcc/cannabis/",
  },
  {
    state: "Rhode Island",
    abbreviation: "RI",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g",
    possessionLimitMed: "2.5 oz / 71g",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per person (3 mature); 12 per household",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public places; private residence only",
    recentChanges: "Rhode Island Cannabis Act enacted 2022; retail adult-use sales launched Dec 2023; social equity licensing in progress",
    regulatoryUrl: "https://dbr.ri.gov/cannabis-control-commission",
  },
  {
    state: "Vermont",
    abbreviation: "VT",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g",
    possessionLimitMed: "2 oz / 56g per 30 days",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per household (2 mature)",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; private property only",
    recentChanges: "Retail adult-use market continuing expansion; Cannabis Control Board overseeing new licenses; social equity provisions active",
    regulatoryUrl: "https://ccb.vermont.gov/",
  },
  {
    state: "Virginia",
    abbreviation: "VA",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g",
    possessionLimitMed: "4 oz / 113g per 30 days",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "4 plants per household",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; private property only",
    recentChanges: "Possession legal since 2021; retail sales framework enacted 2024; Cannabis Control Authority established; dispensary licensing ongoing for 2025",
    regulatoryUrl: "https://www.cca.virginia.gov/",
  },
  {
    state: "Washington",
    abbreviation: "WA",
    legalStatus: "Fully Legal",
    recreationalLegal: true,
    medicalLegal: true,
    possessionLimitRec: "1 oz / 28g flower; 7g concentrate; 16 oz edibles",
    possessionLimitMed: "3 oz / 85g flower; 48 oz edibles (with authorization)",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "6 plants per patient (medical only); recreational home grow enacted 2025",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public and in view of the public; private property only",
    recentChanges: "Home grow for recreational users signed into law 2025 (HB 1510); social equity task force recommendations implemented",
    regulatoryUrl: "https://lcb.wa.gov/mjlicense/marijuana-702",
  },

  // ─── MEDICAL ONLY ──────────────────────────────────────────────────────────────
  {
    state: "Alabama",
    abbreviation: "AL",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "70 daily dosages per 30 days (no smokable flower)",
    ageRequirement: 19,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited; medical use only in private; no smoking or vaping allowed",
    recentChanges: "Darren Wesley 'Ato' Hall Compassion Act (SB 46) passed 2021; AMCC licensing repeatedly delayed; first dispensary sales began late 2024",
    regulatoryUrl: "https://amcc.alabama.gov/",
  },
  {
    state: "Arkansas",
    abbreviation: "AR",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "2.5 oz / 71g per 14-day period",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical patients may consume in private residences",
    recentChanges: "Issue 4 (recreational legalization) failed in Nov 2022; medical program expansions ongoing; additional dispensary licenses issued",
    regulatoryUrl: "https://www.healthy.arkansas.gov/programs-services/topics/medical-marijuana",
  },
  {
    state: "Florida",
    abbreviation: "FL",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "2.5 oz / 71g smokable flower per 35 days; additional non-smokable allowance",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical patients use in private only",
    recentChanges: "Amendment 3 (recreational legalization) narrowly failed Nov 2024 with 57% (needed 60%); medical program expanded; home grow legislation pending",
    regulatoryUrl: "https://knowthefactsmmj.com/",
  },
  {
    state: "Kentucky",
    abbreviation: "KY",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "Determined by practitioner; 8 oz per fill",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; private use for cardholders only; no smoking allowed",
    recentChanges: "SB 47 signed 2023 establishing medical cannabis program; dispensary sales began January 2025; no smokable flower initially",
    regulatoryUrl: "https://kymedcan.ky.gov/",
  },
  {
    state: "Louisiana",
    abbreviation: "LA",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "2.5 oz / 71g smokable cannabis per 14 days",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical patients may use in private residences",
    recentChanges: "Smokable flower became available 2022; third-party pharmacy distribution expanded; possession decriminalized under certain thresholds",
    regulatoryUrl: "https://ldaf.louisiana.gov/office-of-medical-marijuana/",
  },
  {
    state: "Mississippi",
    abbreviation: "MS",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "3.5 oz / 99g per month (up to 6 oz for terminal illness)",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical use in private only",
    recentChanges: "SB 2095 (Mississippi Medical Cannabis Act) signed 2022; dispensaries operational since 2024; patient registration ongoing",
    regulatoryUrl: "https://www.msdh.ms.gov/page/30,0,400.html",
  },
  {
    state: "New Hampshire",
    abbreviation: "NH",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "2 oz / 56g per 10-day period",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical patients may use in private; possession decriminalized up to 3/4 oz",
    recentChanges: "Recreational legalization bills have repeatedly passed the House but stalled in the Senate; decriminalization in effect since 2017",
    regulatoryUrl: "https://www.dhhs.nh.gov/programs-services/medicinal-and-therapeutic-cannabis",
  },
  {
    state: "North Dakota",
    abbreviation: "ND",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "2.5 oz / 71g per 30 days",
    ageRequirement: 19,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical use in private only",
    recentChanges: "Measure 2 (recreational legalization) failed Nov 2022; medical program expanded with additional dispensaries",
    regulatoryUrl: "https://www.health.nd.gov/mm",
  },
  {
    state: "Oklahoma",
    abbreviation: "OK",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "3 oz / 85g on person; 8 oz at home; 1 oz concentrate",
    ageRequirement: 18,
    homeGrowAllowed: true,
    homeGrowLimit: "6 mature, 6 seedling plants per patient",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical patients may consume in private",
    recentChanges: "SQ 820 (recreational legalization) failed March 2023; OMMA enacted stricter licensing; moratorium on new dispensary licenses",
    regulatoryUrl: "https://omma.ok.gov/",
  },
  {
    state: "Pennsylvania",
    abbreviation: "PA",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "30-day supply as determined by physician",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical patients only in private; no smoking (vape and other forms permitted)",
    recentChanges: "Flower added to medical program 2018; recreational legalization bills introduced but not passed; Governor Shapiro supportive of adult use",
    regulatoryUrl: "https://www.health.pa.gov/topics/programs/Medical%20Marijuana/Pages/Medical%20Marijuana.aspx",
  },
  {
    state: "South Dakota",
    abbreviation: "SD",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "3 oz / 85g",
    ageRequirement: 21,
    homeGrowAllowed: true,
    homeGrowLimit: "3 plants per patient (if 150+ miles from dispensary)",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical use in private residences only",
    recentChanges: "Amendment A (recreational) overturned by courts; IM 27 (recreational) failed Nov 2022; medical program operational since 2021",
    regulatoryUrl: "https://doh.sd.gov/cannabis/",
  },
  {
    state: "Utah",
    abbreviation: "UT",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "113g unprocessed flower per 30 days (medical card required)",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited everywhere in public; medical patients consume in private only",
    recentChanges: "Prop 2 modified by Utah Medical Cannabis Act; additional pharmacies licensed; home delivery pilot initiated",
    regulatoryUrl: "https://medicalcannabis.utah.gov/",
  },
  {
    state: "West Virginia",
    abbreviation: "WV",
    legalStatus: "Medical Only",
    recreationalLegal: false,
    medicalLegal: true,
    possessionLimitRec: "N/A",
    possessionLimitMed: "30-day supply as determined by physician",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "Dispensaries",
    publicConsumption: "Prohibited in public; medical patients may consume in private; no smoking of raw plant material allowed",
    recentChanges: "Medical Cannabis Act passed 2017; first dispensary sales began 2024 after extended delays; additional grower/processor licenses issued",
    regulatoryUrl: "https://dhhr.wv.gov/bph/Pages/Medical-Cannabis-Program.aspx",
  },

  // ─── DECRIMINALIZED ────────────────────────────────────────────────────────────
  {
    state: "Nebraska",
    abbreviation: "NE",
    legalStatus: "Decriminalized",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; possession of 1 oz or less is an infraction (citation and fine)",
    recentChanges: "Medical cannabis initiative passed by voters Nov 2024 but faces legal challenges; decriminalization statute unchanged since 1978",
    regulatoryUrl: "https://dhhs.ne.gov/",
  },
  {
    state: "North Carolina",
    abbreviation: "NC",
    legalStatus: "Decriminalized",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; possession of 0.5 oz or less is a misdemeanor with no jail time (fine only)",
    recentChanges: "SB 711 (Compassionate Care Act) passed Senate 2023 but stalled in House; hemp-derived THC products under new regulation",
    regulatoryUrl: "https://www.ncleg.gov/",
  },

  // ─── ILLEGAL ───────────────────────────────────────────────────────────────────
  {
    state: "Georgia",
    abbreviation: "GA",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A (low-THC oil up to 5% THC for registered patients)",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; all cannabis possession is illegal; low-THC oil program has very limited access",
    recentChanges: "Low-THC oil commission (HB 324) operational since 2023; full medical or recreational programs not enacted; local decriminalization in Atlanta",
    regulatoryUrl: "https://ltg.georgia.gov/georgia-access-medical-cannabis-commission",
  },
  {
    state: "Idaho",
    abbreviation: "ID",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; all cannabis is illegal with no medical or decriminalization provisions",
    recentChanges: "No significant cannabis reform legislation passed; constitutional amendment proposed to permanently ban recreational cannabis",
    regulatoryUrl: "https://legislature.idaho.gov/",
  },
  {
    state: "Indiana",
    abbreviation: "IN",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; all cannabis possession is illegal; CBD oil with 0.3% THC or less is legal",
    recentChanges: "Multiple medical cannabis bills introduced but not passed; interim study committee reviewed cannabis policy in 2024",
    regulatoryUrl: "https://www.in.gov/isdh/",
  },
  {
    state: "Iowa",
    abbreviation: "IA",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A (limited medical cannabidiol program: 4.5g THC per 90 days)",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; very limited medical cannabidiol program exists but traditional cannabis remains illegal",
    recentChanges: "Medical cannabidiol program THC cap remains at 4.5g per 90 days; recreational and broader medical bills have not advanced",
    regulatoryUrl: "https://idph.iowa.gov/omc",
  },
  {
    state: "Kansas",
    abbreviation: "KS",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; all cannabis possession is illegal",
    recentChanges: "Medical cannabis bill (SB 135) passed Senate in 2024 but did not advance in House; decriminalization efforts unsuccessful",
    regulatoryUrl: "https://www.kslegislature.org/",
  },
  {
    state: "South Carolina",
    abbreviation: "SC",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; all cannabis possession is illegal; first offense possession is a misdemeanor",
    recentChanges: "S. 150 (Compassionate Care Act for medical cannabis) passed Senate 2022 and 2024 but stalled in House repeatedly",
    regulatoryUrl: "https://www.scstatehouse.gov/",
  },
  {
    state: "Tennessee",
    abbreviation: "TN",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; all cannabis is illegal; limited CBD-only access for specific conditions",
    recentChanges: "Medical cannabis bill proposed by Rep. Faison in 2024 but did not pass; limited hemp-derived cannabinoid regulation enacted",
    regulatoryUrl: "https://www.tn.gov/health.html",
  },
  {
    state: "Texas",
    abbreviation: "TX",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A (Compassionate Use Program: low-THC cannabis up to 1% THC for qualifying conditions)",
    ageRequirement: 18,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; very limited Compassionate Use Program (low-THC); general cannabis possession is illegal",
    recentChanges: "HB 1805 expanded Compassionate Use qualifying conditions in 2023; broader medical and recreational efforts stalled in legislature",
    regulatoryUrl: "https://www.dshs.texas.gov/texas-compassionate-use-act",
  },
  {
    state: "Wisconsin",
    abbreviation: "WI",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; possession is illegal statewide though some municipalities have local decriminalization",
    recentChanges: "Governor Evers included legalization in budget proposals; Republican legislature has blocked all cannabis reform; local municipalities passed decriminalization ordinances",
    regulatoryUrl: "https://www.dhs.wisconsin.gov/",
  },
  {
    state: "Wyoming",
    abbreviation: "WY",
    legalStatus: "Illegal",
    recreationalLegal: false,
    medicalLegal: false,
    possessionLimitRec: "N/A",
    possessionLimitMed: "N/A",
    ageRequirement: 21,
    homeGrowAllowed: false,
    homeGrowLimit: "Not allowed",
    purchaseLocations: "N/A",
    publicConsumption: "Prohibited; all cannabis possession is illegal; no medical or decriminalization provisions",
    recentChanges: "No significant cannabis reform legislation advanced; decriminalization and medical bills introduced but consistently defeated",
    regulatoryUrl: "https://wyoleg.gov/",
  },
];
